Replace deprecated syntax with curly braces for accessing  array and …
jweiland-net/glossary2 pull request #31
Opened 2021-05-12 10:43 UTC by julianhofmann

…string offset

2021-05-12 13:02 UTC, froemken requested changes

2021-05-12 13:02 UTC, froemken commented on Classes/Controller/GlossaryController.php
> +        $letter = strtr(mb_strtolower($glossary->getTitle()[0]), 'äöü', 'aou');
Hi @julianhofmann 

thank you for this PR. As you see I work with mb_strtolower here and I don't know, if [0] supports multi byte, too.
Can you please use mb_substr(title, 0, 1) to get the first letter?

Nice greetings

Stefan

2021-05-12 14:08 UTC, froemken approved these changes

2021-05-12 14:12 UTC, froemken commented
WTF `Unknown database 'test_ft6279efb'`

I have the same issue with maps2 today. Don't get it as it works for TYPO3 9.5 branch?!?!

I will invest some time on friday.

Stefan

2021-05-12 14:57 UTC, julianhofmann commented
Strange things with TYPO3 10.4.16? Had today troubles with non initialized ObjectStorages after update 10.4.15 -> 10.4.16. Maybe, you can try it with v10.4.15.

2021-05-21 20:52 UTC, froemken commented
Hi @julianhofmann 

I have found the problem:
https://github.com/jweiland-net/glossary2/blob/master/.github/workflows/ci.yml#L57-L59

Can you please update to latest master and build PR again?

Thank you

Stefan

2021-09-18 00:44 UTC, froemken commented
Today I have created a new branch for TYPO3 9 called TYPO3_9-5. It contains a versions which is compatible with TYPO3 9 and 10.
In this branch I have just uploaded a patch which make use of mb_substr to get first letter. This version is tagged with 4.3.3.

I will release this version in TER on monday

Have a nice weekend

Stefan

2021-09-18 00:44 UTC, closed without merging