Typo3 13 compatibility
jweiland-net/glossary2 pull request #72
Opened 2024-10-15 13:34 UTC by hojalatheef

2024-10-23 07:23 UTC, sfroemkenjw commented on .github/workflows/ci.yml
> +        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -d mysql -s functional
Can we add PostgreSQL here?

2024-11-04 12:45 UTC, sfroemkenjw requested changes

2024-11-04 12:45 UTC, sfroemkenjw commented on Classes/Event/ModifyQueryOfSearchGlossariesEvent.php
>  class ModifyQueryOfSearchGlossariesEvent
Since PHP 8.2 we can use `readonly` classes

2024-11-04 12:45 UTC, sfroemkenjw commented on Classes/Event/PostProcessFirstLettersEvent.php
>      public function setFirstLetters(array $firstLetters): void
Do we need that setter? Is that called from somewhere?

2024-11-04 12:45 UTC, sfroemkenjw commented on Classes/Service/GlossaryService.php
> +     * @return ConstraintInterface
Only add parameters, if they contain additional information or where needed by PhpStan

```suggestion
```

2024-11-04 12:45 UTC, sfroemkenjw commented on Classes/Service/GlossaryService.php
> +     * @param string $columnAlias
```suggestion
```

2024-11-04 12:45 UTC, sfroemkenjw commented on Classes/Service/GlossaryService.php
> +        return $GLOBALS['TYPO3_REQUEST'];
Please add ServerRequestFactory::fromGlobals(), if TYPO3_REQUEST is NULL

2024-11-04 12:45 UTC, sfroemkenjw commented on Classes/Updates/GlossarySlugUpdater.php
> +namespace JWeiland\Glossary2\Updates;
Singular. Please use "Update" or "Upgrade". If you change that name, please also update the directory name

2024-11-04 12:45 UTC, sfroemkenjw commented on Classes/Updates/MoveOldFlexFormSettingsUpdater.php
> +namespace JWeiland\Glossary2\Updates;
Wrong classname

2024-11-04 12:45 UTC, sfroemkenjw commented on Configuration/TCA/Overrides/tt_content.php
> +$pluginSignature = ExtensionUtility::registerPlugin(
Do not add variables into global space. Wrap into call_user_func

2024-11-04 12:45 UTC, sfroemkenjw commented on Configuration/page.tsconfig
> +@import 'EXT:telephonedirectory/Configuration/TSconfig/ContentElementWizard.tsconfig'
telephonedirectory?

2024-11-04 12:45 UTC, sfroemkenjw commented on Documentation/Settings.cfg
> +version     = 7.0.0
Switch to guidex.xml

2024-11-04 12:45 UTC, sfroemkenjw commented on README.md
> +[extension-ter-url]: https://extensions.typo3.org/extension/telephonedirectory/
telephonedirectory?

2024-11-04 12:45 UTC, sfroemkenjw commented on README.md
> +[LICENSE_BADGE]: https://img.shields.io/github/license/jweiland-net/telephonedirectory?label=license&style=for-the-badge
telephonedirectory?

2024-11-04 12:45 UTC, sfroemkenjw commented on composer.json
> +	"homepage": "https://www.jweiland.net",
no "www."

2024-11-04 12:45 UTC, sfroemkenjw commented on composer.json
> +		"typo3/cms-install": "^13.4.0"
Why is cms-install needed?

2024-11-04 15:50 UTC, hojalatheef commented on Classes/Domain/Repository/GlossaryRepository.php
> + * @extends Repository<Glossary>
Repository<Glossary> tells tools that this repository will handle Glossary objects.
If its not there Level 6 Stan check will throw 

```
  Line   Classes/Domain/Repository/GlossaryRepository.php                                                                                                                             
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  27     Class JWeiland\Glossary2\Domain\Repository\GlossaryRepository extends generic class TYPO3\CMS\Extbase\Persistence\Repository but does not specify its types: T               
  71     Parameter #1 $extbaseQuery of class JWeiland\Glossary2\Event\ModifyQueryOfSearchGlossariesEvent constructor expects TYPO3\CMS\Extbase\Persistence\QueryResultInterface<int,  
         JWeiland\Glossary2\Domain\Model\Glossary>, TYPO3\CMS\Extbase\Persistence\QueryResultInterface<int, TYPO3\CMS\Extbase\DomainObject\DomainObjectInterface> given.              
 ------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
```

2024-11-04 16:12 UTC, sfroemkenjw commented on Classes/Domain/Repository/GlossaryRepository.php
> + * @extends Repository<Glossary>
I have asked multiple KIs. "extends" is correct. Personnel I don't get it, but I mark it resolved.

2024-11-06 23:18 UTC, hojalatheef commented on Classes/PageTitleProvider/Glossary2PageTitleProvider.php
> +    protected function getPluginArgumentsFromRequest(ServerRequestInterface $requestObject): mixed
You're Rights

2024-11-06 23:20 UTC, hojalatheef commented on Classes/Event/PostProcessFirstLettersEvent.php
>      public function setFirstLetters(array $firstLetters): void
No So I removed the setters

2024-11-12 12:58 UTC, hojalatheef commented on composer.json
> +		"typo3/cms-install": "^13.4.0"
@sfroemkenjw 
It's required because if it's not included. PHP stan throws an error.

![image](https://github.com/user-attachments/assets/0e115e62-5936-4aa4-b691-92e6072c5eef)

So I put it back now

2024-11-12 14:25 UTC, sfroemkenjw commented on Build/phpunit/UnitTestsBootstrap.php
> +    // @todo: Remove else branch when dropping support for v12
ext_emconf.php does not support TYPO3 12 anymore. So, else can be removed now, right?

2024-11-12 14:29 UTC, sfroemkenjw commented on Classes/Controller/GlossaryController.php
> +        if (is_array($this->request->getAttribute('currentContentObject')->data)) {
`getAttribute` may return `null`. Please test against ContentObjectRenderer before accessing `data`

2024-11-12 14:38 UTC, sfroemkenjw commented on Classes/Update/GlossarySlugUpdater.php
> +namespace JWeiland\Glossary2\Update;
Rename file to `GlossarySlugUpdate`

2024-11-12 14:39 UTC, sfroemkenjw commented on Classes/Update/MoveOldFlexFormSettingsUpdater.php
> +namespace JWeiland\Glossary2\Update;
Rename file to `MoveOldFlexFormSettingsUpdate`

2024-11-12 14:42 UTC, sfroemkenjw commented on Configuration/TCA/Overrides/tt_content.php
> +    $pluginSignature = ExtensionUtility::registerPlugin(
`list_type` is deprecated: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86253/24/typo3/sysext/core/Documentation/Changelog/13.4/Deprecation-105076-PluginContentElementAndPluginSubTypes.rst

2024-11-12 14:46 UTC, sfroemkenjw commented on Tests/Functional/Repository/GlossaryRepositoryTest.php
> +            $this->objectManager,
ObjectManager? IMO it was removed with TYPO3 12.

2024-11-12 14:47 UTC, sfroemkenjw commented on Tests/Functional/Service/GlossaryServiceTest.php
> +    //#[Test]
Disabled tests? Why. Can you repair it?

2024-11-13 11:56 UTC, sfroemkenjw commented on Build/phpstan/phpstan-baseline.neon
> +			#	message: '#^Access to an undefined property TYPO3\\\\CMS\\\\Scheduler\\\\Task\\\\AbstractTask$#'
As everything is deprecated here, can we remove that file? Or just remove the last two lines?

2024-11-13 11:59 UTC, sfroemkenjw requested changes

2024-11-13 11:59 UTC, sfroemkenjw commented on Classes/Update/MoveOldFlexFormSettingsUpdater.php
> +namespace JWeiland\Glossary2\Update;
File contains still "Updater"

2024-11-13 20:26 UTC, merged